controller: improve the mechanism of disk removing
harvester/node-disk-manager pull request #102
Opened 2024-05-10 17:23 UTC by Vicente-Cheng

**Problem:**
When the disk is gone, we cannot remove it on Harvester UI.
That's a regression after we introduce the inactive/corrupted concept.

**Solution:**
Improve the removing disk mechanism.

**Related Issue:**
https://github.com/harvester/harvester/issues/5726

**Test plan:**
1. Create 3 node Harvester cluster
2. add an extra disk and provision it as Longhorn disk
3. remove the above disk (physically). (If you use kvm, try virtctl command with attach-device/detach-device)
4. Remove this provision disk on the Harvester UI
5. make sure both Harvester/Longhorn UI removed the above disk

2024-05-16 08:18 UTC, Vicente-Cheng commented
> I think I understand this :-) and it looks reasonable. I just have a couple of questions:
> 
> 1. It looks like if the call to `utils.ForceUmountWithTimeout()` fails due to timeout, then the disk won't be removed from the node. Given that we _do_ want to remove  inactive or corrupted disks from the node, would it make sense to ignore timeout failures and remove the disk anyway?

Ah... good catch, I should not return. Maybe just log and continue the remove op with longhorn node.
Let me update again...

> 2. I gave this a rough test by attaching a disk to harvester running in a VM, then I let it be provisioned, detached the disk, rebooted that node, waited for it to come up showing a failed disk, and then finally I updated node-disk-manager to a build I did of this PR. The failed/missing disk was automatically removed from the node (when viewed via the Harvester UI), and from Longhorn. So that all works fine. But, it's still present as a blockdevice CR. Is that correct? Or should the CR be deleted as well?

Yeah, currently, the blockdevice CR needs to be deleted manually. There are some reasons I did not delete blockdevice CRD with any delete operations.

1. for hotplug case, the blockdevice will change the state from inactive -> active.
2. for corruption cases, the block device needs to keep recording the corruption flag. Then, we could try to repair and reuse manually.


But I also wonder we need to refine the whole flow. I will create a HEP to redefine the NDM on v1.4.0 to decompose the component like the provisioned. I thought we could discuss more at that time.

2024-05-17 05:08 UTC, tserong approved these changes

2024-05-17 10:19 UTC, votdev requested changes

2024-05-17 10:19 UTC, votdev commented on pkg/controller/blockdevice/controller.go
> +	// handle remove device no matter interactive or corrupted, we will set `device.Spec.FileSystem.Provisioned` to false
```suggestion
	// handle remove device no matter inactive or corrupted, we will set `device.Spec.FileSystem.Provisioned` to false
```

2024-05-17 10:19 UTC, votdev commented on pkg/controller/blockdevice/controller.go
> +			logrus.Debugf("Update block device %s after removeing", device.Name)
```suggestion
			logrus.Debugf("Update block device %s after removing", device.Name)
```

2024-05-17 10:19 UTC, votdev commented on pkg/utils/utils.go
> +		_, err := executeOnHostNamespaceWithTimeout("umount", []string{path, "-f"}, timeout)
I think it is best practice to set the command options first and at last the device file.
```suggestion
		_, err := executeOnHostNamespaceWithTimeout("umount", []string{"-f", path}, timeout)
```

2024-05-17 10:19 UTC, votdev commented on pkg/utils/utils.go
> +func executeOnHostNamespaceWithTimeout(cmd string, args []string, cmdTimeout time.Duration) (string, error) {
I know it's no fun and it's a chore to document functions, but I'm wondering what is returned by the function. In case of an error I see an empty string, but on success? I can only answer this question if I look at what executor.Execute returns. As a developer I should be able to use the function `executeOnHostNamespaceWithTimeout` without having to do a code review and research the functions used.

2024-05-20 06:31 UTC, Vicente-Cheng commented on pkg/controller/blockdevice/controller.go
> +	// handle remove device no matter interactive or corrupted, we will set `device.Spec.FileSystem.Provisioned` to false
updated, thanks!

2024-05-20 06:31 UTC, Vicente-Cheng commented on pkg/controller/blockdevice/controller.go
> +			logrus.Debugf("Update block device %s after removeing", device.Name)
ditto

2024-05-20 06:31 UTC, Vicente-Cheng commented on pkg/utils/utils.go
> +		_, err := executeOnHostNamespaceWithTimeout("umount", []string{path, "-f"}, timeout)
Nice catch, updated!

2024-05-21 08:37 UTC, votdev approved these changes

2024-05-21 08:52 UTC, merged

2024-05-21 09:23 UTC, Vicente-Cheng commented
@mergifyio backport v0.6.x