Decompose the provisioner
harvester/node-disk-manager pull request #109
Opened 2024-06-05 09:54 UTC by Vicente-Cheng

**Problem:**
To support various storage backends.

**Solution:**
Decompose the provisioner, we could define various behaviors for each provisioner

**Related Issue:**
TBD

**Test plan:**
Make sure all operations work as usual

2024-06-11 03:50 UTC, Vicente-Cheng commented
CodeFactor complains about files generated by wangler. (the redundant `return` of deepcopy func)

2024-06-11 06:30 UTC, votdev commented on deploy/charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> +                  Longhornv2 or LocalLVM"
Is `LocalLVM` a typo? I am asking because some lines below in the properties you are using `Longhornv2 or LVM`.

2024-06-11 06:31 UTC, votdev commented on manifests/crds/harvesterhci.io_blockdevices.yaml
> +                      Longhornv2 or LVM"
`LocalLVM`or `LVM`?

2024-06-11 06:32 UTC, votdev commented on deploy/charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> +                  Longhornv2 or LocalLVM"
LocalLVMor LVM?

2024-06-11 06:32 UTC, votdev commented on manifests/crds/harvesterhci.io_blockdevices.yaml
> +                  Longhornv2 or LocalLVM"
LocalLVMor LVM?

2024-06-11 06:34 UTC, votdev commented on pkg/apis/harvesterhci.io/v1beta1/types.go
> +	// a string with the provisioner name, e.g. "Longhornv1, Longhornv2 or LocalLVM"
`LocalLVM` or `LVM`? Some lines below you are using `LVM`.

2024-06-11 16:01 UTC, Vicente-Cheng commented on deploy/charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> +                  Longhornv2 or LocalLVM"
yeah, this is a typo. Sorry, I missed these comments. updated to all

2024-06-20 06:56 UTC, Yu-Jack commented on pkg/provisioner/lvm.go
> +func NewLVMProvisioner(vgName string, device *diskv1.BlockDevice, blockInfo block.Info, semaphoreObj *Semaphore) *LVMProvisioner {
Since these provisioners only have private variables (LVM & Longhorn), and you also have the interface here. You could do following changes:

1. Convert `LVMProvisioner` `LonghornV1Provisioner` to private.
2. Use interface as return in `NewLVMProvisioner` `NewLHV1Provisioner`

For example:

```suggestion
func NewLVMProvisioner(vgName string, device *diskv1.BlockDevice, blockInfo block.Info, semaphoreObj *Semaphore) Provisioner {
```

2024-06-20 06:56 UTC, Yu-Jack commented on pkg/provisioner/lvm.go
> +}
Just share another concept. We could use embedded struct to de-duplicate some codes.

```go
type provisioner struct {
	name      string
	blockInfo block.Info
	device    *diskv1.BlockDevice
}

func (p *provisioner) GetProvisionerName() string {
	return p.name
}

type LonghornV1Provisioner struct {
	*provisioner

	// other ... blablabla
}

type LVMProvisioner struct {
	*provisioner

	// other ... blablabla
}
```

Then you don't need to create common functions for each provisioner, such as `GetProvisionerName`. The reason I bring this is we'll have longhorn v2 engine in the future like you mentioned. It could reduce some repeated code if we need.

2024-06-20 07:13 UTC, Yu-Jack commented on pkg/provisioner/common.go
> +	return "Unknown OP"
I think we could make use of default?

```suggestion
	case NeedMountUpdateUnmount:
		return "Unmount"
	default:
		return "Unknown OP"
	}
```

2024-06-20 07:13 UTC, Yu-Jack commented on pkg/provisioner/lvm.go
> +func doVGActivate() error {
I found these codes look similar, I think we could extract one more common function?

```go
func executeCommandWithNamespace(cmd string, args []string) error {
	ns := utils.GetHostNamespacePath(utils.HostProcPath)
	executor, err := utils.NewExecutorWithNS(ns)
	if err != nil {
		return fmt.Errorf("generate executor failed. %v", err)
	}

	_, err = executor.Execute(cmd, args)
	if err != nil {
		return fmt.Errorf("%s failed. %v", cmd, err)
	}
	return nil
}

func doPVCreate(devPath string) error {
	return executeCommandWithNamespace("pvcreate", []string{devPath})
}

func doVGCreate(devPath, vgName string) error {
	return executeCommandWithNamespace("vgcreate", []string{vgName, devPath})
}

func doVGActivate() error {
	return executeCommandWithNamespace("vgchange", []string{"--activate", "y"})
}
```

2024-06-20 07:30 UTC, Vicente-Cheng commented on pkg/provisioner/lvm.go
> +func NewLVMProvisioner(vgName string, device *diskv1.BlockDevice, blockInfo block.Info, semaphoreObj *Semaphore) *LVMProvisioner {
good suggestion, updated!

2024-06-20 07:32 UTC, Vicente-Cheng commented on pkg/provisioner/lvm.go
> +}
Thanks for the suggestion. That could help to reduce the duplicated common function! Updated!

2024-06-20 07:32 UTC, Vicente-Cheng commented on pkg/provisioner/common.go
> +	return "Unknown OP"
sure, updated!

2024-06-20 07:33 UTC, Vicente-Cheng commented on pkg/provisioner/lvm.go
> +func doVGActivate() error {
Thanks for the suggestion, updated!

2024-06-25 07:53 UTC, tserong reviewed
Why is the provisioner info duplicated in both the CR spec and status sections? Doesn't this only need to be set in the spec?

2024-06-28 06:55 UTC, Yu-Jack commented on pkg/controller/blockdevice/controller.go
> +	return nil, fmt.Errorf("unsupported provisioner type %s", provisionerType)
NIT: you could use switch default

2024-08-13 09:31 UTC, Vicente-Cheng commented on pkg/controller/blockdevice/controller.go
> +	return nil, fmt.Errorf("unsupported provisioner type %s", provisionerType)
updated, thanks!

2024-08-13 09:33 UTC, Vicente-Cheng commented on deploy/charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> +    - jsonPath: .status.deviceStatus.devPath
The `spec.DevPath` means the dev path when we create the blockdevice CRD (means the first time and fixed)
The `status.deviceStatus.devPath` means the current dev path.

So I thought showing the `status.deviceStatus.devPath` seems more useful for us.

2024-08-14 03:24 UTC, Yu-Jack approved these changes
LGTM, thanks.

2024-08-14 06:42 UTC, tserong commented on deploy/charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> +    - jsonPath: .status.deviceStatus.devPath
Yeah showing the actual current path makes sense.

I've just realised this (kinda) explains https://github.com/harvester/harvester/issues/6224 where there were discrepancies between `spec.DevPath` and `status.deviceStatus.devPath`. I mean, there never should have been three BDs that all had the same `status.deviceStatus.devPath`, and I assume that was (somehow) caused by multiple dodgy devices with the same WWN, but the fact that one is the path when the device was added, and one is the current path, at least sheds some light on the discrepancies I noticed in that issue.

Thinking aloud: Maybe we should just drop `spec.DevPath`? Does it help at all to know what the path was originally? Note: I'm _not_ suggesting we make any further changes to this PR in this area. Just an item for thought/consideration later.

2024-08-14 06:48 UTC, Vicente-Cheng commented on deploy/charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> +    - jsonPath: .status.deviceStatus.devPath
>Maybe we should just drop spec.DevPath

+1, it's a redundant field for me with the current design.
We can do more cleanup for these fields. I plan to introduce a new naming mechanism to replace the current one in the next release (means v1.5). That we would be good at some devices w/o wwn. Maybe we could redesign these fields at that time.

We still need to check the WWN duplicated. But we could have better handling with those devices w/o wwn.

2024-08-14 15:11 UTC, bk201 commented on pkg/apis/harvesterhci.io/v1beta1/types.go
> +	VgName string `json:"vgName,omitempty"`
VgName is the required field for the LVM provisioner, but we may need more fields in the future. If every provisioner adds their fields in this structure, we'll have a lot of fields in the same level, and hard to tell which provisioner owns the field.

How about adding the provisioners' structures like this:

```
type ProvisionerInfo struct {
  LVMProvisionerInfo *LVMProvisionerInfo
  
  Provisioner2Info *Provisioner2Info

  Provisioner3Info *Provisioner3Info
}
```

Similar to the design of Volume source in the kubevirt VM: https://github.com/harvester/harvester/blob/88e05afc3a2a497b8b5cf76554d698a403ba7de1/vendor/kubevirt.io/api/core/v1/schema.go#L776

2024-08-15 02:08 UTC, Vicente-Cheng commented on pkg/apis/harvesterhci.io/v1beta1/types.go
> +	Provisioner *ProvisionerStatus `json:"provisioner,omitempty"`
agree, I want to use status to do some validation.
But it seems we will need a webhook. I could do the validation on the webhook.

2024-08-15 02:11 UTC, Vicente-Cheng commented on deploy/charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> +                      (only worked for LVM)
no need to fix with the new provisioner field

2024-08-15 02:11 UTC, Vicente-Cheng commented on deploy/charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> +                      (only worked for LVM)
ditto

2024-08-15 02:11 UTC, Vicente-Cheng commented on pkg/provisioner/common.go
> +	TypeLonghornV2 = "Longhornv2"
thanks for the suggestion, updated!

2024-08-15 02:11 UTC, Vicente-Cheng commented on pkg/apis/harvesterhci.io/v1beta1/types.go
> +	VgName string `json:"vgName,omitempty"`
Thanks for the suggestion, updated!

2024-08-15 05:50 UTC, tserong approved these changes

2024-08-15 10:57 UTC, votdev commented on deploy/charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> +    - jsonPath: .status.deviceStatus.devPath
> Can these two values ever be different?

Yes. If you have a device file like `/dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:0:0` this can change when the PCI slots are reordered, e.g. by adding new hardware.

2024-08-15 11:24 UTC, Vicente-Cheng commented on deploy/charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> +    - jsonPath: .status.deviceStatus.devPath
Thanks @votdev,
Yeah, if we would like to keep the spec.devPath field. We should use a meaningful path like the above instead of the `/dev/sdx`. As I mentioned above, we could redesign the field and naming mechanism on v1.5.

2024-08-15 13:43 UTC, votdev requested changes

2024-08-15 13:43 UTC, votdev commented on pkg/apis/harvesterhci.io/v1beta1/types.go
> +	// a string with the volume name for the provisioner
Is this correct? Does `EngineVersion` not contain a engine version string?

2024-08-15 13:43 UTC, votdev commented on pkg/provisioner/common.go
> +	// Return values: bool1: isFormatComplete, bool2: isNeedRequeue, error: error
Does this sound better? If changed, adapt the following occurrences as well.
```suggestion
	// Return values: bool1: isFormatComplete, bool2: isRequeueNeeded, error: error
```

2024-08-15 13:43 UTC, votdev commented on pkg/provisioner/common.go
> +			if device.Status.DeviceStatus.Details.StorageController == string(diskv1.StorageControllerNVMe) {
Maybe add some links as references here:
- https://en.wikipedia.org/wiki/World_Wide_Name#Formats
- https://wiki.archlinux.org/title/Persistent_block_device_naming#by-id_and_by-path

2024-08-15 13:43 UTC, votdev commented on pkg/provisioner/common.go
> +			path, err := filepath.EvalSymlinks("/dev/disk/by-uuid/" + fsUUID)
Maybe add a link to a reference that explains how the device file should look like, e.g. https://wiki.archlinux.org/title/Persistent_block_device_naming#by-uuid

2024-08-15 13:43 UTC, votdev commented on pkg/provisioner/common.go
> +			return filepath.EvalSymlinks("/dev/disk/by-uuid/" + ptUUID)
Add a reference link, e.g. https://wiki.archlinux.org/title/Persistent_block_device_naming#by-partuuid

2024-08-15 13:43 UTC, votdev commented on pkg/provisioner/longhornv1.go
> +			logrus.Warnf("The disk spec should not different between longhorn node and blockdevice CRD, disk: %+v, diskSpec: %+v", disk, diskSpec)
```suggestion
			logrus.Warnf("The disk spec should not differ between longhorn node and blockdevice CRD, disk: %+v, diskSpec: %+v", disk, diskSpec)
```

2024-08-15 13:43 UTC, votdev commented on pkg/provisioner/longhornv1.go
> +		msg := fmt.Sprintf("Disk not in longhorn node `%s`", p.nodeObj.Name)
`Longhorn` is a product name, thus it should be title-case. Every occurrence across all files should be adapted.
```suggestion
		msg := fmt.Sprintf("Disk not in Longhorn node `%s`", p.nodeObj.Name)
```

2024-08-15 13:43 UTC, votdev commented on pkg/provisioner/longhornv1.go
> +		return fmt.Errorf("partitioned device is not supported, please use raw block device instead")
```suggestion
		return fmt.Errorf("Partitioned device is not supported, please use raw block device instead")
```

2024-08-15 13:43 UTC, votdev commented on pkg/provisioner/longhornv1.go
> +		logrus.Infof("unmount %s for %s", filesystem.MountPoint, device.Name)
```suggestion
		logrus.Infof("Unmount %s for %s", filesystem.MountPoint, device.Name)
```

2024-08-15 13:43 UTC, votdev commented on pkg/provisioner/longhornv1.go
> +	logrus.Debugf("make ext4 filesystem format of device %s", device.Name)
I don't want to appear small-minded. I think the beginning of a sentence should start with a capital letter.
This should be adapted for all code changes. I will therefore spare myself any further comments in this regard.
```suggestion
	logrus.Debugf("Make ext4 filesystem format of device %s", device.Name)
```

2024-08-15 15:39 UTC, bk201 approved these changes

2024-08-16 00:21 UTC, tserong commented on pkg/provisioner/longhornv1.go
> +		return fmt.Errorf("partitioned device is not supported, please use raw block device instead")
Actually, because this is an error string it shouldn't be capitalised (see https://go.dev/wiki/CodeReviewComments#error-strings)

2024-08-16 00:23 UTC, tserong commented on pkg/provisioner/longhornv1.go
> +	logrus.Debugf("make ext4 filesystem format of device %s", device.Name)
I suspect this is form is probably habit related to error strings being uncapitalized. In this case though it's a log message (not an error string) so I agree it should be a proper sentence.

2024-08-16 02:57 UTC, Vicente-Cheng commented on pkg/provisioner/longhornv1.go
> +	logrus.Debugf("make ext4 filesystem format of device %s", device.Name)
Thanks, I correct the above logs. For others, we could do it on another PR.

2024-08-16 02:59 UTC, Vicente-Cheng commented on pkg/provisioner/longhornv1.go
> +		return fmt.Errorf("partitioned device is not supported, please use raw block device instead")
Thanks @tserong. We will keep this for the error log.

2024-08-16 02:59 UTC, Vicente-Cheng commented on pkg/provisioner/longhornv1.go
> +		msg := fmt.Sprintf("Disk not in longhorn node `%s`", p.nodeObj.Name)
done

2024-08-16 02:59 UTC, Vicente-Cheng commented on pkg/provisioner/longhornv1.go
> +			logrus.Warnf("The disk spec should not different between longhorn node and blockdevice CRD, disk: %+v, diskSpec: %+v", disk, diskSpec)
done

2024-08-16 03:01 UTC, Vicente-Cheng commented on pkg/provisioner/common.go
> +			if device.Status.DeviceStatus.Details.StorageController == string(diskv1.StorageControllerNVMe) {
I added the related info link on WWN and filesystem UUID. 
Partition is departed. We will remove that in the next version.

2024-08-16 03:01 UTC, Vicente-Cheng commented on pkg/provisioner/common.go
> +	// Return values: bool1: isFormatComplete, bool2: isNeedRequeue, error: error
done

2024-08-16 03:01 UTC, Vicente-Cheng commented on deploy/charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> +                        description: a string with the volume name for the provisioner
Nice catch! updated!

2024-08-16 03:02 UTC, Vicente-Cheng commented on deploy/charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> +                description: a string list with device tag for provisioner, e.g. ["default",
updated!

2024-08-16 03:02 UTC, Vicente-Cheng commented on pkg/apis/harvesterhci.io/v1beta1/types.go
> +	// a string with the volume name for the provisioner
updated!

2024-08-16 09:50 UTC, votdev commented on pkg/provisioner/longhornv1.go
> +		return fmt.Errorf("partitioned device is not supported, please use raw block device instead")
Sorry, missed to remove that comment because of the reason mentioned by Tim.

2024-08-21 11:44 UTC, votdev approved these changes
LGTM

2024-08-21 17:13 UTC, merged

2024-08-21 17:14 UTC, Vicente-Cheng commented
@mergifyio backport v0.7.x

2024-08-28 06:00 UTC, votdev commented
I have a question. We have the scenario that certain labels, e.g. “topology.kubernetes.io/zone” for host resources, are automatically synchronized to Longhorn. Is this scenario considered in this PR and the interface design?