Add webhook to ensure the VGStatus is active
harvester/node-disk-manager pull request #161
Opened 2024-10-24 01:37 UTC by Vicente-Cheng

**Problem:**
We need to fix the multiple times wipefs, which might break the metadata.
Also, add the webhook to ensure the VGStatus is active.

**Solution:**
add the webhook to ensure the VGStatus is active
ensure we only execute wipefs before pvcreate

**Related Issue:**

**Test plan:**

2024-10-24 07:42 UTC, bk201 approved these changes

2024-10-28 05:28 UTC, tserong requested changes
One small suggestion, otherwise LGTM.

2024-10-28 05:28 UTC, tserong commented on pkg/provisioner/lvm.go
> +	l.lock.Unlock()
This should probably be `defer l.lock.Unlock()` and moved to immediately after line 74, else any error above will result in the lock remaining in place.

2024-10-28 06:45 UTC, Vicente-Cheng commented on pkg/provisioner/lvm.go
> +	l.lock.Unlock()
nice catch!
I originally wanted to reduce the lock scope, so I did not use defer func (but yes, I missed the error handling)
It looks like it did not have a huge difference with/ lock the whole function, so like you mentioned, defer function would be nice.
Thanks!

2024-10-28 07:00 UTC, tserong approved these changes

2024-10-28 07:20 UTC, Vicente-Cheng commented
@mergifyio backport v0.7.x

2024-10-28 07:20 UTC, merged