Update devpath if changed
harvester/node-disk-manager pull request #36
Opened 2022-04-27 09:42 UTC by weihanglo

When reboot, device path might change but controller cannot detect it
during the reconcilation, we explicitly check the value in scanner.

related: https://github.com/harvester/harvester/issues/2149#issuecomment-1110488173

2022-04-27 14:16 UTC, bk201 requested changes

2022-04-27 14:16 UTC, bk201 commented on pkg/controller/blockdevice/scanner.go
> +				logrus.Debugf("Enqueue block device %s for device patch change", bd.Name)
```suggestion
				logrus.Debugf("Enqueue block device %s for device path change", bd.Name)
```

2022-04-28 00:40 UTC, bk201 approved these changes
LGTM

2022-04-28 04:33 UTC, johnliu55tw approved these changes
Verified dev path is updated. LGTM

2022-04-28 04:42 UTC, merged