[wait for #1] Periodic rescanning for blockdevices
harvester/node-disk-manager pull request #5
Opened 2021-09-06 07:33 UTC by weihanglo

Wait for #1. Please review from 9ee49fe

## What

Add periodic rescanning for blockdevices
                                                                     
- A new CLI flag `--rescan-interval`. Default to 60 seconds
- A simple periodic blockdevice rescanning mechanism that reuses the
  logic of good old `RegisterNodeBlockDevices`

2021-09-07 07:10 UTC, guangbochen approved these changes
LGTM

2021-09-07 09:24 UTC, bk201 commented on main.go
> +		},
nit: will be nice to support EnvVars too. Easier to use than args in some cases.

2021-09-07 09:57 UTC, weihanglo commented on main.go
> +		},
@bk201
fixed at a518a88, thanks.

2021-09-07 11:20 UTC, bk201 requested changes

2021-09-07 11:20 UTC, bk201 commented on pkg/controller/blockdevice/controller.go
> +		if newBd, err := c.MakeGPTPartitionIfNeeded(bd); err != nil {
This will automatically create GPT partition on un-identified disks (e.g. virtio disks).
We better have an option to enable/disable this feature.

2021-09-07 12:05 UTC, weihanglo commented on pkg/controller/blockdevice/controller.go
> +		if newBd, err := c.MakeGPTPartitionIfNeeded(bd); err != nil {
Good suggestion. It's also straightforward to add such an option. The questions are:

1. If this feature is disabled, what is the expected behaviour? IMO throwing out the error directly is a good choice.
2. Should this option be enabled by default? If this defaults to enabled, then I guess people whould keep it as is until they hit the wall of auto-create-gpt-partition.

2021-09-07 14:42 UTC, bk201 commented on pkg/controller/blockdevice/controller.go
> +		if newBd, err := c.MakeGPTPartitionIfNeeded(bd); err != nil {
Logging an error is good. Will a BlockDevice resource be created in this situation? If yes, maybe setting conditions also works.

I'd recommend disabling the feature by default. Do not touch users' disks unless they agree.

2021-09-08 01:38 UTC, weihanglo commented on pkg/controller/blockdevice/controller.go
> +		if newBd, err := c.MakeGPTPartitionIfNeeded(bd); err != nil {
No. If it cannot identify a disk, a block device won't be generated.
I think logging errors and disabling the feature by default are great.

cc @guangbochen. What do you think?

2021-09-08 03:06 UTC, guangbochen commented on pkg/controller/blockdevice/controller.go
> +		if newBd, err := c.MakeGPTPartitionIfNeeded(bd); err != nil {
Yep, LGTM, IIRC when the user mounts the entire single block device to the node, we will create the GPT table and partition of that disk, correct?

2021-09-08 03:08 UTC, weihanglo commented on pkg/controller/blockdevice/controller.go
> +		if newBd, err := c.MakeGPTPartitionIfNeeded(bd); err != nil {
Correct. I just pushed a commit f629cca for this new option. Thanks for the suggestion @bk201

2021-09-08 04:05 UTC, bk201 approved these changes
LGTM! Thanks!

2021-09-08 04:38 UTC, merged